name: Build

on:
  push:
  schedule:
    - cron: '0 8 * * 0'

jobs:
  GNU:
    name: GNU-${{ matrix.gnu_ver }}-${{ matrix.build_type }}

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        gnu_ver: [10, 11]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - name: Install gfortran
      run: |
        sudo apt install -y gfortran-${{ matrix.gnu_ver }}
    - name: Configuring
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_Fortran_COMPILER=gfortran-${{ matrix.gnu_ver }} \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Building
      run: make -C build -j$(nproc)

  Intel:
    name: Intel-${{ matrix.build_type }}

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Intel compilers
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
          sudo apt install --no-install-recommends intel-oneapi-compiler-fortran
          source /opt/intel/oneapi/setvars.sh
          printenv >> $GITHUB_ENV
      - name: Configuring
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_Fortran_COMPILER=ifort -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Building
        run: make -C build -j$(nproc)

  Nvidia:
    name: Nvidia-${{ matrix.build_type }}

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Nvidia Compiler Files
        id: cache-nvidia
        uses: actions/cache@v2
        with:
          path: |
            ./nvhpc-21-5_21.5_amd64.deb
            ./nvhpc-2021_21.5_amd64.deb
          key: nvidia-${{ hashFiles('*.deb') }}
      - name: Download Nvidia Compiler Files
        if: steps.cache-nvidia.outputs.cache-hit != 'true'
        run: |
          wget https://developer.download.nvidia.com/hpc-sdk/21.5/nvhpc-21-5_21.5_amd64.deb \
               https://developer.download.nvidia.com/hpc-sdk/21.5/nvhpc-2021_21.5_amd64.deb
      - name: Install Nvidia Compiler
        run: |
          sudo apt-get install -y ./nvhpc-21-5_21.5_amd64.deb ./nvhpc-2021_21.5_amd64.deb
          echo "/opt/nvidia/hpc_sdk/Linux_x86_64/21.5/compilers/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/21.5/compilers/lib" >> $GITHUB_ENV
      - name: Configuring
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_Fortran_COMPILER=nvfortran -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
      - name: Building
        run: make -C build -j$(nproc)
